// Catalogue NUTRIOCUS — 94 produits de l'effort
export type Product = {
  t: "Boisson" | "Gel" | "Barre" | "Compote" | "Gommes" | "Gaufre";
  m: string;
  n: string;
  g: number;
  s: number;
  c: number;
  b: number;
  r: string;
  com: string;
  l: string;
  custom?: boolean;
};

export const PRODUCTS_CATALOG: Product[] = [
  { t: "Barre", m: "Apurna", n: "Barre moelleuse énergétique", g: 24, s: 56, c: 0, b: 1300, r: "1:0.3", com: "Barre intéressante pour des apports en glucides compris entre 60 et 75 grammes de glucides par heure d'effort.", l: "https://www.apurna-nutrition.fr/ecommerce/fr/endurance/483-lot-5-barres-moelleuses-framboise-noisettes.html" },
  { t: "Boisson", m: "Apurna", n: "Hydratation Energie", g: 35, s: 304, c: 0, b: 0, r: "1:0.3", com: "Boisson intéressante pour les traileurs et coureurs avec un apport en glucides inférieur à 75g par heure.", l: "https://www.apurna-nutrition.fr/ecommerce/fr/endurance/40-boisson-hydratation-orange-3288111982874.html" },
  { t: "Boisson", m: "Apurna", n: "Longue Distance", g: 37, s: 305, c: 0, b: 1000, r: "1:0.3", com: "Boisson intéressante avec apport en BCAA.", l: "https://www.apurna-nutrition.fr/ecommerce/fr/endurance/450-boisson-hydratation-longue-distance-orange-3288111982928.html" },
  { t: "Gel", m: "Apurna", n: "Longue Distance", g: 21, s: 50, c: 0, b: 200, r: "1:0.3", com: "Gel intéressant pour les traileurs et coureurs avec des apports compris entre 60 et 75g.", l: "https://www.apurna-nutrition.fr/ecommerce/fr/endurance/229-gel-energie-longue-distance-pomme-3288111982522.html" },
  { t: "Barre", m: "Apurna", n: "Barre fondante Energie", g: 16, s: 25, c: 0, b: 500, r: "1:0.5", com: "Barre pour 75-90 g/h.", l: "https://www.apurna-nutrition.fr/ecommerce/fr/endurance/31-barres-energie-citron-amande-3288110267682.html" },
  { t: "Gel", m: "Apurna", n: "Passage difficile", g: 20, s: 50, c: 21, b: 0, r: "1:0.5", com: "Gel avec caféine modérée.", l: "https://www.apurna-nutrition.fr/ecommerce/fr/endurance/156-gel-energie-passage-difficile-guarana-cola-3288111982560.html" },
  { t: "Compote", m: "Atlet", n: "Purée énergétique", g: 9, s: 80, c: 0, b: 800, r: "1:0", com: "Pour efforts très longue durée.", l: "https://atletnutrition.com/puree-energetique-bio/50-puree-energetique-bio-butternut-3770010324119.html" },
  { t: "Barre", m: "Atlet", n: "Endurance énergie", g: 13, s: 48, c: 0, b: 2000, r: "1:0.3", com: "Apport BCAA intéressant.", l: "https://atletnutrition.com/barres-energetiques-bio/21-barre-energetique-biologique-amande-3770010324034.html" },
  { t: "Barre", m: "Atlet", n: "Barre salé Energie", g: 11, s: 140, c: 0, b: 1000, r: "1:0.3", com: "Pour très longues durées.", l: "https://atletnutrition.com/barres-energetiques-bio/39-barre-salee-energetique-biologique-noix-cajou-pistache-3770010324096.html" },
  { t: "Boisson", m: "Atlet", n: "Effort Endurance", g: 36, s: 300, c: 0, b: 0, r: "1:0.3", com: "Pour apports <75g/h.", l: "https://atletnutrition.com/boissons-energetiques-bio/26-boisson-energetique-biologique-nutrition-sportive-3770010324010.html" },
  { t: "Gel", m: "Atlet", n: "Effort Endurance", g: 18, s: 80, c: 0, b: 0, r: "1:0.3", com: "Gel 60-75 g/h.", l: "https://atletnutrition.com/gels-energetiques-bio/41-gel-energetique-biologique-fruits-rouges-3770010324102.html" },
  { t: "Compote", m: "Atlet", n: "Endurance Energie", g: 26, s: 8, c: 0, b: 0, r: "1:0.5", com: "Compote 75-90 g/h.", l: "https://atletnutrition.com/compotes-energetiques-bio/83-compote-energetique-bio-pomme-fraise-3770010324379.html" },
  { t: "Compote", m: "Baouw", n: "Patate douce Carotte Poivre", g: 17, s: 398, c: 0, b: 200, r: "1:0.3", com: "Salé. 60-75 g/h.", l: "https://www.baouw-organic-nutrition.com/" },
  { t: "Barre", m: "Baouw", n: "Barre protéinée", g: 18, s: 7, c: 0, b: 1275, r: "1:0.5", com: "Apport BCAA intéressant.", l: "https://www.baouw-organic-nutrition.com/" },
  { t: "Barre", m: "Baouw", n: "Barre Mangue Cajou", g: 29, s: 50, c: 0, b: 160, r: "1:0.5", com: "Barre 60-90 g/h.", l: "https://www.baouw-organic-nutrition.com/" },
  { t: "Barre", m: "Baouw", n: "Barre Framboise Pistache", g: 25, s: 13, c: 0, b: 270, r: "1:0.5", com: "Barre 60-90 g/h.", l: "https://www.baouw-organic-nutrition.com/" },
  { t: "Compote", m: "Baouw", n: "Mangue Passion Gingembre", g: 19, s: 11, c: 0, b: 0, r: "1:0.5", com: "Compote 75-90 g/h.", l: "https://www.baouw-organic-nutrition.com/" },
  { t: "Boisson", m: "Baouw", n: "Energy Drink", g: 38, s: 350, c: 0, b: 1000, r: "1:0.8", com: "Pour apports >90 g/h.", l: "https://www.baouw-organic-nutrition.com/" },
  { t: "Gel", m: "Baouw", n: "Gel énergétique", g: 30, s: 4, c: 0, b: 0, r: "1:0.8", com: "Gel >80 g/h.", l: "https://www.baouw-organic-nutrition.com/" },
  { t: "Barre", m: "Décathlon", n: "Aptonia", g: 14, s: 32, c: 0, b: 200, r: "1:0", com: "Apports <60 g/h.", l: "https://www.decathlon.fr/" },
  { t: "Gel", m: "Décathlon", n: "Energy Gel", g: 23, s: 24, c: 0, b: 0, r: "1:0", com: "Gel <60 g/h.", l: "https://www.decathlon.fr/" },
  { t: "Gel", m: "Décathlon", n: "Energy Gel + Cola", g: 22, s: 52, c: 20, b: 240, r: "1:0", com: "Gel + caféine légère.", l: "https://www.decathlon.fr/" },
  { t: "Barre", m: "Décathlon", n: "Dattes barre", g: 20, s: 20, c: 0, b: 500, r: "1:0.3", com: "Barre 60-75 g/h.", l: "https://www.decathlon.fr/" },
  { t: "Boisson", m: "Décathlon", n: "Iso +", g: 33, s: 400, c: 0, b: 300, r: "1:0.3", com: "Pour <75 g/h.", l: "https://www.decathlon.fr/" },
  { t: "Barre", m: "Décathlon", n: "Barres aux amandes", g: 14, s: 52, c: 0, b: 500, r: "1:0.5", com: "Barre amandes.", l: "https://www.decathlon.fr/" },
  { t: "Boisson", m: "Décathlon", n: "Iso", g: 35, s: 288, c: 0, b: 0, r: "1:0.5", com: "Boisson 70-90 g/h.", l: "https://www.decathlon.fr/" },
  { t: "Boisson", m: "Décathlon", n: "Etixx", g: 31, s: 276, c: 0, b: 0, r: "1:0.5", com: "Boisson 70-90 g/h.", l: "https://www.decathlon.fr/" },
  { t: "Gommes", m: "Décathlon", n: "Pâte de fruit énergétique", g: 21, s: 40, c: 0, b: 0, r: "1:0.5", com: "Gommes 60-90 g/h.", l: "https://www.decathlon.fr/" },
  { t: "Barre", m: "Maurten", n: "Solid 160", g: 40, s: 244, c: 0, b: 700, r: "1:0.5", com: "Barre 60-90 g/h.", l: "https://www.maurten.com/" },
  { t: "Boisson", m: "Maurten", n: "Drink Mix 160", g: 39, s: 525, c: 0, b: 0, r: "1:0.5", com: "Boisson 70-90 g/h.", l: "https://www.maurten.com/" },
  { t: "Boisson", m: "Maurten", n: "Drink Mix 320", g: 78, s: 620, c: 0, b: 0, r: "1:0.7", com: "Pour apports >90 g/h.", l: "https://www.maurten.com/" },
  { t: "Boisson", m: "Maurten", n: "Drink Mix 320 CAF 100", g: 79, s: 620, c: 100, b: 0, r: "1:0.7", com: "Avec caféine.", l: "https://www.maurten.com/" },
  { t: "Gel", m: "Maurten", n: "Gel Maurten 100", g: 25, s: 50, c: 0, b: 0, r: "1:0.8", com: "Gel >90 g/h.", l: "https://www.maurten.com/" },
  { t: "Gel", m: "Maurten", n: "Gel Maurten 100 CAF 100", g: 25, s: 55, c: 100, b: 0, r: "1:0.8", com: "Avec caféine.", l: "https://www.maurten.com/" },
  { t: "Gel", m: "Maurten", n: "Gel Maurten 160", g: 40, s: 80, c: 0, b: 0, r: "1:0.8", com: "Gel >90 g/h.", l: "https://www.maurten.com/" },
  { t: "Barre", m: "Meltonic", n: "Tonic Barre Pistache", g: 13, s: 226, c: 0, b: 500, r: "1:0.3", com: "Barre 60-75 g/h.", l: "https://www.meltonic.com/" },
  { t: "Barre", m: "Meltonic", n: "Pur'Barre Cajou", g: 26, s: 238, c: 0, b: 1500, r: "1:0.3", com: "Barre 60-75 g/h.", l: "https://www.meltonic.com/" },
  { t: "Boisson", m: "Meltonic", n: "Boisson Antioxydante", g: 32, s: 260, c: 0, b: 0, r: "1:0.3", com: "Boisson <75 g/h.", l: "https://www.meltonic.com/" },
  { t: "Compote", m: "Meltonic", n: "Purée salée", g: 2.2, s: 40, c: 0, b: 2000, r: "1:0.5", com: "Tres longue durée.", l: "https://www.meltonic.com/" },
  { t: "Gel", m: "Meltonic", n: "Antioxydant", g: 15, s: 2, c: 0, b: 0, r: "1:0.5", com: "Gel 75-90 g/h.", l: "https://www.meltonic.com/" },
  { t: "Gel", m: "Meltonic", n: "Caféine", g: 29, s: 0, c: 200, b: 0, r: "1:0.5", com: "Tres riche en caféine.", l: "https://www.meltonic.com/" },
  { t: "Barre", m: "Naak", n: "Ultra Energy", g: 28, s: 180, c: 0, b: 2000, r: "1:0.3", com: "Apport BCAA.", l: "https://www.naak.com/" },
  { t: "Boisson", m: "Naak", n: "Ultra Energy", g: 55, s: 400, c: 0, b: 0, r: "1:0.3", com: "Boisson <75 g/h.", l: "https://www.naak.com/" },
  { t: "Compote", m: "Naak", n: "Patate douce Courge", g: 26, s: 171, c: 0, b: 1000, r: "1:0.3", com: "Compote 60-75 g/h.", l: "https://www.naak.com/" },
  { t: "Gaufre", m: "Naak", n: "Ultra Energy", g: 16, s: 140, c: 0, b: 600, r: "1:0.3", com: "Gaufre 40-75 g/h.", l: "https://www.naak.com/" },
  { t: "Gel", m: "Naak", n: "Gel chocolat", g: 27, s: 190, c: 35, b: 235, r: "1:0.3", com: "Avec caféine légère.", l: "https://www.naak.com/" },
  { t: "Gel", m: "Naak", n: "Gel Sirop d'érable", g: 27, s: 200, c: 0, b: 235, r: "1:0.3", com: "Gel 60-75 g/h.", l: "https://www.naak.com/" },
  { t: "Boisson", m: "Naak", n: "Boost Energy", g: 60, s: 260, c: 0, b: 0, r: "1:0.5", com: "Boisson 70-90 g/h.", l: "https://www.naak.com/" },
  { t: "Compote", m: "Naak", n: "Pomme et Sirop d'érable", g: 26, s: 162, c: 0, b: 1000, r: "1:0.5", com: "Compote 75-90 g/h.", l: "https://www.naak.com/" },
  { t: "Gel", m: "Naak", n: "Boost Gel", g: 25, s: 112, c: 0, b: 0, r: "1:0.5", com: "Gel 75-90 g/h.", l: "https://www.naak.com/" },
  { t: "Barre", m: "Nduranz", n: "Training Bar", g: 30, s: 0, c: 0, b: 400, r: "1:0.8", com: "Pour apports >90 g/h.", l: "https://4endurance.fr/" },
  { t: "Boisson", m: "Nduranz", n: "Nrgy Unit Drink", g: 45, s: 288, c: 0, b: 0, r: "1:0.8", com: "Boisson >90 g/h.", l: "https://4endurance.fr/" },
  { t: "Boisson", m: "Nduranz", n: "Nrgy Unit Drink 90", g: 90, s: 288, c: 0, b: 0, r: "1:0.8", com: "Boisson tres concentrée.", l: "https://4endurance.fr/" },
  { t: "Boisson", m: "Nduranz", n: "Drink 45 Prototype", g: 45, s: 460, c: 0, b: 0, r: "1:0.8", com: "Sodium élevé.", l: "https://4endurance.fr/" },
  { t: "Gel", m: "Nduranz", n: "Nrgy Gel 45", g: 45, s: 460, c: 0, b: 0, r: "1:0.8", com: "Gel concentré.", l: "https://4endurance.fr/" },
  { t: "Gel", m: "Nduranz", n: "Nrgy Gel CAF cerise", g: 45, s: 460, c: 65, b: 0, r: "1:0.8", com: "Avec caféine.", l: "https://4endurance.fr/" },
  { t: "Gel", m: "Nduranz", n: "Nrgy Gel CAF café", g: 45, s: 460, c: 130, b: 0, r: "1:0.8", com: "Tres concentré caféine.", l: "https://4endurance.fr/" },
  { t: "Gel", m: "Nduranz", n: "Nrgy Gel 22.5", g: 22.5, s: 5, c: 0, b: 0, r: "1:0.8", com: "Gel >80 g/h.", l: "https://4endurance.fr/" },
  { t: "Gommes", m: "Nduranz", n: "Juice Bar", g: 22.5, s: 0, c: 0, b: 0, r: "1:0.8", com: "Gommes >90 g/h.", l: "https://4endurance.fr/" },
  { t: "Gommes", m: "Nduranz", n: "Chew Bar", g: 22.5, s: 0, c: 0, b: 0, r: "1:0.8", com: "Gommes >90 g/h.", l: "https://4endurance.fr/" },
  { t: "Boisson", m: "Nutripure", n: "Maltodextrine", g: 40, s: 0, c: 0, b: 0, r: "1:0", com: "Pour <70 g/h. A saler.", l: "https://www.nutripure.fr/" },
  { t: "Barre", m: "Nutripure", n: "Long Distance", g: 31, s: 54, c: 0, b: 200, r: "1:0.5", com: "Barre 60-90 g/h.", l: "https://www.nutripure.fr/" },
  { t: "Boisson", m: "Nutripure", n: "Long Distance 30g", g: 33, s: 770, c: 0, b: 2465, r: "1:0.5", com: "Boisson 70-90 g/h.", l: "https://www.nutripure.fr/" },
  { t: "Boisson", m: "Nutripure", n: "Long Distance 60g", g: 61, s: 800, c: 0, b: 1000, r: "1:0.5", com: "Boisson 70-90 g/h.", l: "https://www.nutripure.fr/" },
  { t: "Gel", m: "Nutripure", n: "Long Distance", g: 30, s: 53, c: 0, b: 0, r: "1:0.5", com: "Gel 75-90 g/h.", l: "https://www.nutripure.fr/" },
  { t: "Barre", m: "Overstim", n: "Barre Ultra", g: 28, s: 98, c: 0, b: 800, r: "1:0.3", com: "Apport BCAA.", l: "https://www.overstims.com/" },
  { t: "Barre", m: "Overstim", n: "Authentic Bar", g: 25, s: 70, c: 0, b: 1300, r: "1:0.3", com: "Apport BCAA.", l: "https://www.overstims.com/" },
  { t: "Barre", m: "Overstim", n: "Origin Bar", g: 16, s: 233, c: 0, b: 1300, r: "1:0.3", com: "Apport BCAA.", l: "https://www.overstims.com/" },
  { t: "Boisson", m: "Overstim", n: "Hydrixir Ultra", g: 31, s: 437, c: 0, b: 1000, r: "1:0.3", com: "Boisson <75 g/h.", l: "https://www.overstims.com/" },
  { t: "Boisson", m: "Overstim", n: "Hydrixir Antioxydant", g: 37, s: 302, c: 0, b: 0, r: "1:0.3", com: "Boisson <75 g/h.", l: "https://www.overstims.com/" },
  { t: "Gel", m: "Overstim", n: "Energix", g: 26, s: 45, c: 0, b: 204, r: "1:0.3", com: "Gel 40-75 g/h.", l: "https://www.overstims.com/" },
  { t: "Gel", m: "Overstim", n: "Coup de fouet", g: 26, s: 45, c: 0, b: 0, r: "1:0.3", com: "Gel 40-75 g/h.", l: "https://www.overstims.com/" },
  { t: "Barre", m: "Overstim", n: "Amélix", g: 15, s: 15, c: 0, b: 300, r: "1:0.5", com: "Pâte de fruit.", l: "https://www.overstims.com/" },
  { t: "Gel", m: "Overstim", n: "Antioxydant", g: 26, s: 68, c: 0, b: 0, r: "1:0.5", com: "Gel 75-90 g/h.", l: "https://www.overstims.com/" },
  { t: "Gommes", m: "Overstim", n: "Pâte de fruit", g: 19, s: 0, c: 0, b: 0, r: "1:0.8", com: "Pour >90 g/h.", l: "https://www.overstims.com/" },
  { t: "Barre", m: "Powerbar", n: "Energize Original", g: 39, s: 210, c: 0, b: 2000, r: "1:0.5", com: "Barre 60-90 g/h.", l: "https://www.powerbar.eu/" },
  { t: "Barre", m: "Powerbar", n: "Ride Energy", g: 25, s: 172, c: 0, b: 5000, r: "1:0.5", com: "Tres riche en BCAA.", l: "https://www.powerbar.eu/" },
  { t: "Barre", m: "Powerbar", n: "Energize Advanced", g: 39, s: 88, c: 0, b: 1000, r: "1:0.5", com: "Barre 60-90 g/h.", l: "https://www.powerbar.eu/" },
  { t: "Gel", m: "Powerbar", n: "Powergel", g: 26, s: 206, c: 0, b: 0, r: "1:0.5", com: "Gel 75-90 g/h.", l: "https://www.powerbar.eu/" },
  { t: "Boisson", m: "Precision Fuel", n: "Drink Mix Carb Only", g: 60, s: 0, c: 0, b: 0, r: "1:0.5", com: "A saler.", l: "https://pfandh.fr/" },
  { t: "Boisson", m: "Precision Fuel", n: "Drink Mix Carb & Electrolytes", g: 60, s: 1000, c: 0, b: 0, r: "1:0.5", com: "Boisson 60-90 g/h.", l: "https://pfandh.fr/" },
  { t: "Gel", m: "Precision Fuel", n: "PF30", g: 30, s: 0, c: 0, b: 0, r: "1:0.5", com: "A saler.", l: "https://pfandh.fr/" },
  { t: "Gel", m: "Precision Fuel", n: "PF30 CAF", g: 30, s: 0, c: 100, b: 0, r: "1:0.5", com: "Caféine + à saler.", l: "https://pfandh.fr/" },
  { t: "Gel", m: "Precision Fuel", n: "PF90", g: 90, s: 0, c: 0, b: 0, r: "1:0.5", com: "Tres concentré, à saler.", l: "https://pfandh.fr/" },
  { t: "Gommes", m: "Precision Fuel", n: "Chew PF30", g: 30, s: 0, c: 0, b: 0, r: "1:0.5", com: "Gommes 75-90 g/h.", l: "https://pfandh.fr/" },
  { t: "Gommes", m: "Precision Fuel", n: "Chew PF60", g: 60, s: 0, c: 0, b: 0, r: "1:0.5", com: "Gommes 75-90 g/h.", l: "https://pfandh.fr/" },
  { t: "Gel", m: "SiS", n: "GO isotonic", g: 22, s: 6, c: 0, b: 0, r: "1:0", com: "Pour 1-2H.", l: "https://4endurance.fr/" },
  { t: "Boisson", m: "SiS", n: "GO Electrolytes", g: 36, s: 237, c: 0, b: 0, r: "1:0.3", com: "Boisson <75 g/h.", l: "https://www.materiel-velo.com/" },
  { t: "Boisson", m: "SiS", n: "Beta Fuel", g: 80, s: 0, c: 0, b: 0, r: "1:0.8", com: "Tres concentré, à saler.", l: "https://www.materiel-velo.com/" },
  { t: "Gel", m: "SiS", n: "Beta fuel", g: 40, s: 20, c: 0, b: 0, r: "1:0.8", com: "Gel >90 g/h.", l: "https://4endurance.fr/" },
  { t: "Gel", m: "TA", n: "Energy Gel", g: 33, s: 100, c: 0, b: 0, r: "1:0.3", com: "Gel 40-75 g/h.", l: "https://www.ta-energy.com/" },
  { t: "Gommes", m: "TA", n: "Gommes TA", g: 25, s: 230, c: 0, b: 0, r: "1:0.3", com: "Gommes 40-75 g/h.", l: "https://www.ta-energy.com/" },
  { t: "Barre", m: "TA", n: "Energy barre bio", g: 19, s: 78, c: 0, b: 500, r: "1:0.3", com: "Barre 60-75 g/h.", l: "https://www.ta-energy.com/" },
  { t: "Boisson", m: "TA", n: "Isotonic", g: 35, s: 350, c: 0, b: 1000, r: "1:0.3", com: "Boisson <75 g/h.", l: "https://www.ta-energy.com/" },
];
